---
site_name: Symbolic Constraints
site_url: https://abogical.github.io/symconstraints/
theme:
  name: material
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default


    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to system preference

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        import:
        - https://pandas.pydata.org/docs/objects.inv
        options:
          docstring_style: numpy
          members_order: source
          show_root_heading: true
