---
name: Deploy

# build the documentation whenever there are new commits on main
on:
  push:
    branches:
    - main

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Initialize Pants
      uses: pantsbuild/actions/init-pants@main
      with:
        gha-cache-key: v0-py3.12
        named-caches-hash: ${{ hashFiles('3rdparty/python/default.lock') }}
    - run: |
        pants run docs:build

    - uses: actions/upload-pages-artifact@v3
      with:
        path: dist/docs

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary
  # permissions.
  deploy-docs:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - id: deployment
      uses: actions/deploy-pages@v4
